version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
platform: x64
before_build:
- cmd: dotnet restore
build:
  verbosity: quiet
build_script:
  cmd: dotnet build
artifacts:
- path: '**\*.nupkg'
